# Generated by Django 2.0 on 2018-07-09 19:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20180709_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete='auth.User', to=settings.AUTH_USER_MODEL),
        ),
    ]
