# Generated by Django 2.0 on 2018-07-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20180718_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.TextField(null=True),
        ),
    ]
